input_features:
  - name: review
    type: text
    encoder:
      type: auto_transformer
      pretrained_model_name_or_path: bigscience/bloom-3b
      trainable: true
      adapter: lora

output_features:
  - name: sentiment
    type: category

trainer:
  batch_size: 4
  epochs: 3
  gradient_accumulation_steps: 8

backend:
  type: ray
  trainer:
    use_gpu: true
    strategy:
      type: deepspeed
      zero_optimization:
        stage: 3
        offload_optimizer:
          device: cpu
          pin_memory: true
