input_features:
- name: pos_01
  type: category
- name: pos_02
  type: category
- name: pos_03
  type: category
- name: pos_04
  type: category
- name: pos_05
  type: category
- name: pos_06
  type: category
- name: pos_07
  type: category
- name: pos_08
  type: category
- name: pos_09
  type: category
- name: pos_10
  type: category
- name: pos_11
  type: category
- name: pos_12
  type: category
- name: pos_13
  type: category
- name: pos_14
  type: category
- name: pos_15
  type: category
- name: pos_16
  type: category
- name: pos_17
  type: category
- name: pos_18
  type: category
- name: pos_19
  type: category
- name: pos_20
  type: category
- name: pos_21
  type: category
- name: pos_22
  type: category
- name: pos_23
  type: category
- name: pos_24
  type: category
- name: pos_25
  type: category
- name: pos_26
  type: category
- name: pos_27
  type: category
- name: pos_28
  type: category
- name: pos_29
  type: category
- name: pos_30
  type: category
- name: pos_31
  type: category
- name: pos_32
  type: category
- name: pos_33
  type: category
- name: pos_34
  type: category
- name: pos_35
  type: category
- name: pos_36
  type: category
- name: pos_37
  type: category
- name: pos_38
  type: category
- name: pos_39
  type: category
- name: pos_40
  type: category
- name: pos_41
  type: category
- name: pos_42
  type: category
model_type: gbm
output_features:
- name: winner
  type: category
preprocessing:
  split:
    type: fixed
