output_features:
  - name: winner
    type: category
input_features:
  - name: pos_01
    type: category
  - name: pos_02
    type: category
  - name: pos_03
    type: category
  - name: pos_04
    type: category
  - name: pos_05
    type: category
  - name: pos_06
    type: category
  - name: pos_07
    type: category
  - name: pos_08
    type: category
  - name: pos_09
    type: category
  - name: pos_10
    type: category
  - name: pos_11
    type: category
  - name: pos_12
    type: category
  - name: pos_13
    type: category
  - name: pos_14
    type: category
  - name: pos_15
    type: category
  - name: pos_16
    type: category
  - name: pos_17
    type: category
  - name: pos_18
    type: category
  - name: pos_19
    type: category
  - name: pos_20
    type: category
  - name: pos_21
    type: category
  - name: pos_22
    type: category
  - name: pos_23
    type: category
  - name: pos_24
    type: category
  - name: pos_25
    type: category
  - name: pos_26
    type: category
  - name: pos_27
    type: category
  - name: pos_28
    type: category
  - name: pos_29
    type: category
  - name: pos_30
    type: category
  - name: pos_31
    type: category
  - name: pos_32
    type: category
  - name: pos_33
    type: category
  - name: pos_34
    type: category
  - name: pos_35
    type: category
  - name: pos_36
    type: category
  - name: pos_37
    type: category
  - name: pos_38
    type: category
  - name: pos_39
    type: category
  - name: pos_40
    type: category
  - name: pos_41
    type: category
  - name: pos_42
    type: category
combiner:
  type: tabnet
  size: 128 # N_a
  output_size: 16 # N_d
  sparsity: 0.001 # lambda_sparse
  bn_momentum: 0.8 # m_B
  num_steps: 3 # N_steps
  relaxation_factor: 1.2 # gamma
  use_keras_batch_norm: false
  bn_virtual_bs: 256 # B_v
trainer:
  batch_size: 4096 # B
  learning_rate: 0.005
  learning_rate_scheduler:
    decay: exponential
    decay_steps: 2000
    decay_rate: 0.95
preprocessing:
  split:
    type: fixed
