output_features:
  - name: emotion_ids
    type: set
input_features:
  - name: text
    type: text
    encoder: bert
    trainable: True
preprocessing:
  split:
    type: fixed
  text:
    max_sequence_length: 40
trainer:
  batch_size: 64
  learning_rate: 0.00002
  epochs: 5
  learning_rate_warmup_epochs: 0
  optimizer:
    type: adamw
  validation_field: emotion_ids
  validation_metric: jaccard
