input_features:
- name: var3
  type: number
- name: var15
  type: number
- name: imp_ent_var16_ult1
  type: number
- name: imp_op_var39_comer_ult1
  type: number
- name: imp_op_var39_comer_ult3
  type: number
- name: imp_op_var40_comer_ult1
  type: number
- name: imp_op_var40_comer_ult3
  type: number
- name: imp_op_var40_efect_ult1
  type: number
- name: imp_op_var40_efect_ult3
  type: number
- name: imp_op_var40_ult1
  type: number
- name: imp_op_var41_comer_ult1
  type: number
- name: imp_op_var41_comer_ult3
  type: number
- name: imp_op_var41_efect_ult1
  type: number
- name: imp_op_var41_efect_ult3
  type: number
- name: imp_op_var41_ult1
  type: number
- name: imp_op_var39_efect_ult1
  type: number
- name: imp_op_var39_efect_ult3
  type: number
- name: imp_op_var39_ult1
  type: number
- name: imp_sal_var16_ult1
  type: number
- name: ind_var1_0
  type: binary
- name: ind_var1
  type: binary
- name: ind_var2_0
  type: binary
- name: ind_var2
  type: binary
- name: ind_var5_0
  type: binary
- name: ind_var5
  type: binary
- name: ind_var6_0
  type: binary
- name: ind_var6
  type: binary
- name: ind_var8_0
  type: binary
- name: ind_var8
  type: binary
- name: ind_var12_0
  type: binary
- name: ind_var12
  type: binary
- name: ind_var13_0
  type: binary
- name: ind_var13_corto_0
  type: binary
- name: ind_var13_corto
  type: binary
- name: ind_var13_largo_0
  type: binary
- name: ind_var13_largo
  type: binary
- name: ind_var13_medio_0
  type: binary
- name: ind_var13_medio
  type: binary
- name: ind_var13
  type: binary
- name: ind_var14_0
  type: binary
- name: ind_var14
  type: binary
- name: ind_var17_0
  type: binary
- name: ind_var17
  type: binary
- name: ind_var18_0
  type: binary
- name: ind_var18
  type: binary
- name: ind_var19
  type: binary
- name: ind_var20_0
  type: binary
- name: ind_var20
  type: binary
- name: ind_var24_0
  type: binary
- name: ind_var24
  type: binary
- name: ind_var25_cte
  type: binary
- name: ind_var26_0
  type: binary
- name: ind_var26_cte
  type: binary
- name: ind_var26
  type: binary
- name: ind_var25_0
  type: binary
- name: ind_var25
  type: binary
- name: ind_var27_0
  type: binary
- name: ind_var28_0
  type: binary
- name: ind_var28
  type: binary
- name: ind_var27
  type: binary
- name: ind_var29_0
  type: binary
- name: ind_var29
  type: binary
- name: ind_var30_0
  type: binary
- name: ind_var30
  type: binary
- name: ind_var31_0
  type: binary
- name: ind_var31
  type: binary
- name: ind_var32_cte
  type: binary
- name: ind_var32_0
  type: binary
- name: ind_var32
  type: binary
- name: ind_var33_0
  type: binary
- name: ind_var33
  type: binary
- name: ind_var34_0
  type: binary
- name: ind_var34
  type: binary
- name: ind_var37_cte
  type: binary
- name: ind_var37_0
  type: binary
- name: ind_var37
  type: binary
- name: ind_var39_0
  type: binary
- name: ind_var40_0
  type: binary
- name: ind_var40
  type: binary
- name: ind_var41_0
  type: binary
- name: ind_var41
  type: binary
- name: ind_var39
  type: binary
- name: ind_var44_0
  type: binary
- name: ind_var44
  type: binary
- name: ind_var46_0
  type: binary
- name: ind_var46
  type: binary
- name: num_var1_0
  type: number
- name: num_var1
  type: number
- name: num_var4
  type: category
- name: num_var5_0
  type: number
- name: num_var5
  type: number
- name: num_var6_0
  type: number
- name: num_var6
  type: number
- name: num_var8_0
  type: number
- name: num_var8
  type: number
- name: num_var12_0
  type: number
- name: num_var12
  type: number
- name: num_var13_0
  type: number
- name: num_var13_corto_0
  type: number
- name: num_var13_corto
  type: number
- name: num_var13_largo_0
  type: number
- name: num_var13_largo
  type: number
- name: num_var13_medio_0
  type: number
- name: num_var13_medio
  type: number
- name: num_var13
  type: number
- name: num_var14_0
  type: number
- name: num_var14
  type: number
- name: num_var17_0
  type: number
- name: num_var17
  type: number
- name: num_var18_0
  type: number
- name: num_var18
  type: number
- name: num_var20_0
  type: number
- name: num_var20
  type: number
- name: num_var24_0
  type: number
- name: num_var24
  type: number
- name: num_var26_0
  type: number
- name: num_var26
  type: number
- name: num_var25_0
  type: number
- name: num_var25
  type: number
- name: num_op_var40_hace2
  type: number
- name: num_op_var40_hace3
  type: number
- name: num_op_var40_ult1
  type: number
- name: num_op_var40_ult3
  type: number
- name: num_op_var41_hace2
  type: number
- name: num_op_var41_hace3
  type: number
- name: num_op_var41_ult1
  type: number
- name: num_op_var41_ult3
  type: number
- name: num_op_var39_hace2
  type: number
- name: num_op_var39_hace3
  type: number
- name: num_op_var39_ult1
  type: number
- name: num_op_var39_ult3
  type: number
- name: num_var27_0
  type: binary
- name: num_var28_0
  type: binary
- name: num_var28
  type: binary
- name: num_var27
  type: binary
- name: num_var29_0
  type: number
- name: num_var29
  type: number
- name: num_var30_0
  type: number
- name: num_var30
  type: number
- name: num_var31_0
  type: number
- name: num_var31
  type: number
- name: num_var32_0
  type: number
- name: num_var32
  type: number
- name: num_var33_0
  type: number
- name: num_var33
  type: number
- name: num_var34_0
  type: number
- name: num_var34
  type: number
- name: num_var35
  type: number
- name: num_var37_med_ult2
  type: number
- name: num_var37_0
  type: number
- name: num_var37
  type: number
- name: num_var39_0
  type: number
- name: num_var40_0
  type: number
- name: num_var40
  type: number
- name: num_var41_0
  type: number
- name: num_var41
  type: binary
- name: num_var39
  type: number
- name: num_var42_0
  type: number
- name: num_var42
  type: number
- name: num_var44_0
  type: number
- name: num_var44
  type: number
- name: num_var46_0
  type: binary
- name: num_var46
  type: binary
- name: saldo_var1
  type: number
- name: saldo_var5
  type: number
- name: saldo_var6
  type: number
- name: saldo_var8
  type: number
- name: saldo_var12
  type: number
- name: saldo_var13_corto
  type: number
- name: saldo_var13_largo
  type: number
- name: saldo_var13_medio
  type: number
- name: saldo_var13
  type: number
- name: saldo_var14
  type: number
- name: saldo_var17
  type: number
- name: saldo_var18
  type: number
- name: saldo_var20
  type: number
- name: saldo_var24
  type: number
- name: saldo_var26
  type: number
- name: saldo_var25
  type: number
- name: saldo_var28
  type: binary
- name: saldo_var27
  type: binary
- name: saldo_var29
  type: number
- name: saldo_var30
  type: number
- name: saldo_var31
  type: number
- name: saldo_var32
  type: number
- name: saldo_var33
  type: number
- name: saldo_var34
  type: number
- name: saldo_var37
  type: number
- name: saldo_var40
  type: number
- name: saldo_var41
  type: binary
- name: saldo_var42
  type: number
- name: saldo_var44
  type: number
- name: saldo_var46
  type: binary
- name: var36
  type: number
- name: delta_imp_amort_var18_1y3
  type: number
- name: delta_imp_amort_var34_1y3
  type: number
- name: delta_imp_aport_var13_1y3
  type: number
- name: delta_imp_aport_var17_1y3
  type: number
- name: delta_imp_aport_var33_1y3
  type: number
- name: delta_imp_compra_var44_1y3
  type: number
- name: delta_imp_reemb_var13_1y3
  type: number
- name: delta_imp_reemb_var17_1y3
  type: number
- name: delta_imp_reemb_var33_1y3
  type: number
- name: delta_imp_trasp_var17_in_1y3
  type: number
- name: delta_imp_trasp_var17_out_1y3
  type: number
- name: delta_imp_trasp_var33_in_1y3
  type: number
- name: delta_imp_trasp_var33_out_1y3
  type: number
- name: delta_imp_venta_var44_1y3
  type: number
- name: delta_num_aport_var13_1y3
  type: number
- name: delta_num_aport_var17_1y3
  type: number
- name: delta_num_aport_var33_1y3
  type: number
- name: delta_num_compra_var44_1y3
  type: number
- name: delta_num_reemb_var13_1y3
  type: number
- name: delta_num_reemb_var17_1y3
  type: number
- name: delta_num_reemb_var33_1y3
  type: number
- name: delta_num_trasp_var17_in_1y3
  type: number
- name: delta_num_trasp_var17_out_1y3
  type: number
- name: delta_num_trasp_var33_in_1y3
  type: number
- name: delta_num_trasp_var33_out_1y3
  type: number
- name: delta_num_venta_var44_1y3
  type: number
- name: imp_amort_var18_hace3
  type: binary
- name: imp_amort_var18_ult1
  type: number
- name: imp_amort_var34_hace3
  type: binary
- name: imp_amort_var34_ult1
  type: number
- name: imp_aport_var13_hace3
  type: number
- name: imp_aport_var13_ult1
  type: number
- name: imp_aport_var17_hace3
  type: number
- name: imp_aport_var17_ult1
  type: number
- name: imp_aport_var33_hace3
  type: number
- name: imp_aport_var33_ult1
  type: number
- name: imp_var7_emit_ult1
  type: number
- name: imp_var7_recib_ult1
  type: number
- name: imp_compra_var44_hace3
  type: number
- name: imp_compra_var44_ult1
  type: number
- name: imp_reemb_var13_hace3
  type: binary
- name: imp_reemb_var13_ult1
  type: number
- name: imp_reemb_var17_hace3
  type: number
- name: imp_reemb_var17_ult1
  type: number
- name: imp_reemb_var33_hace3
  type: binary
- name: imp_reemb_var33_ult1
  type: number
- name: imp_var43_emit_ult1
  type: number
- name: imp_trans_var37_ult1
  type: number
- name: imp_trasp_var17_in_hace3
  type: number
- name: imp_trasp_var17_in_ult1
  type: number
- name: imp_trasp_var17_out_hace3
  type: binary
- name: imp_trasp_var17_out_ult1
  type: number
- name: imp_trasp_var33_in_hace3
  type: number
- name: imp_trasp_var33_in_ult1
  type: number
- name: imp_trasp_var33_out_hace3
  type: binary
- name: imp_trasp_var33_out_ult1
  type: number
- name: imp_venta_var44_hace3
  type: number
- name: imp_venta_var44_ult1
  type: number
- name: ind_var7_emit_ult1
  type: binary
- name: ind_var7_recib_ult1
  type: binary
- name: ind_var10_ult1
  type: binary
- name: ind_var10cte_ult1
  type: binary
- name: ind_var9_cte_ult1
  type: binary
- name: ind_var9_ult1
  type: binary
- name: ind_var43_emit_ult1
  type: binary
- name: ind_var43_recib_ult1
  type: binary
- name: var21
  type: number
- name: num_var2_0_ult1
  type: binary
- name: num_var2_ult1
  type: binary
- name: num_aport_var13_hace3
  type: number
- name: num_aport_var13_ult1
  type: number
- name: num_aport_var17_hace3
  type: number
- name: num_aport_var17_ult1
  type: number
- name: num_aport_var33_hace3
  type: number
- name: num_aport_var33_ult1
  type: number
- name: num_var7_emit_ult1
  type: number
- name: num_var7_recib_ult1
  type: number
- name: num_compra_var44_hace3
  type: number
- name: num_compra_var44_ult1
  type: number
- name: num_ent_var16_ult1
  type: number
- name: num_var22_hace2
  type: number
- name: num_var22_hace3
  type: number
- name: num_var22_ult1
  type: number
- name: num_var22_ult3
  type: number
- name: num_med_var22_ult3
  type: number
- name: num_med_var45_ult3
  type: number
- name: num_meses_var5_ult3
  type: category
- name: num_meses_var8_ult3
  type: category
- name: num_meses_var12_ult3
  type: category
- name: num_meses_var13_corto_ult3
  type: category
- name: num_meses_var13_largo_ult3
  type: category
- name: num_meses_var13_medio_ult3
  type: number
- name: num_meses_var17_ult3
  type: category
- name: num_meses_var29_ult3
  type: category
- name: num_meses_var33_ult3
  type: category
- name: num_meses_var39_vig_ult3
  type: category
- name: num_meses_var44_ult3
  type: category
- name: num_op_var39_comer_ult1
  type: number
- name: num_op_var39_comer_ult3
  type: number
- name: num_op_var40_comer_ult1
  type: number
- name: num_op_var40_comer_ult3
  type: number
- name: num_op_var40_efect_ult1
  type: number
- name: num_op_var40_efect_ult3
  type: number
- name: num_op_var41_comer_ult1
  type: number
- name: num_op_var41_comer_ult3
  type: number
- name: num_op_var41_efect_ult1
  type: number
- name: num_op_var41_efect_ult3
  type: number
- name: num_op_var39_efect_ult1
  type: number
- name: num_op_var39_efect_ult3
  type: number
- name: num_reemb_var13_hace3
  type: binary
- name: num_reemb_var13_ult1
  type: number
- name: num_reemb_var17_hace3
  type: number
- name: num_reemb_var17_ult1
  type: number
- name: num_reemb_var33_hace3
  type: binary
- name: num_reemb_var33_ult1
  type: number
- name: num_sal_var16_ult1
  type: number
- name: num_var43_emit_ult1
  type: number
- name: num_var43_recib_ult1
  type: number
- name: num_trasp_var11_ult1
  type: number
- name: num_trasp_var17_in_hace3
  type: number
- name: num_trasp_var17_in_ult1
  type: number
- name: num_trasp_var17_out_hace3
  type: binary
- name: num_trasp_var17_out_ult1
  type: number
- name: num_trasp_var33_in_hace3
  type: number
- name: num_trasp_var33_in_ult1
  type: number
- name: num_trasp_var33_out_hace3
  type: binary
- name: num_trasp_var33_out_ult1
  type: number
- name: num_venta_var44_hace3
  type: number
- name: num_venta_var44_ult1
  type: number
- name: num_var45_hace2
  type: number
- name: num_var45_hace3
  type: number
- name: num_var45_ult1
  type: number
- name: num_var45_ult3
  type: number
- name: saldo_var2_ult1
  type: binary
- name: saldo_medio_var5_hace2
  type: number
- name: saldo_medio_var5_hace3
  type: number
- name: saldo_medio_var5_ult1
  type: number
- name: saldo_medio_var5_ult3
  type: number
- name: saldo_medio_var8_hace2
  type: number
- name: saldo_medio_var8_hace3
  type: number
- name: saldo_medio_var8_ult1
  type: number
- name: saldo_medio_var8_ult3
  type: number
- name: saldo_medio_var12_hace2
  type: number
- name: saldo_medio_var12_hace3
  type: number
- name: saldo_medio_var12_ult1
  type: number
- name: saldo_medio_var12_ult3
  type: number
- name: saldo_medio_var13_corto_hace2
  type: number
- name: saldo_medio_var13_corto_hace3
  type: number
- name: saldo_medio_var13_corto_ult1
  type: number
- name: saldo_medio_var13_corto_ult3
  type: number
- name: saldo_medio_var13_largo_hace2
  type: number
- name: saldo_medio_var13_largo_hace3
  type: number
- name: saldo_medio_var13_largo_ult1
  type: number
- name: saldo_medio_var13_largo_ult3
  type: number
- name: saldo_medio_var13_medio_hace2
  type: number
- name: saldo_medio_var13_medio_hace3
  type: binary
- name: saldo_medio_var13_medio_ult1
  type: number
- name: saldo_medio_var13_medio_ult3
  type: number
- name: saldo_medio_var17_hace2
  type: number
- name: saldo_medio_var17_hace3
  type: number
- name: saldo_medio_var17_ult1
  type: number
- name: saldo_medio_var17_ult3
  type: number
- name: saldo_medio_var29_hace2
  type: number
- name: saldo_medio_var29_hace3
  type: number
- name: saldo_medio_var29_ult1
  type: number
- name: saldo_medio_var29_ult3
  type: number
- name: saldo_medio_var33_hace2
  type: number
- name: saldo_medio_var33_hace3
  type: number
- name: saldo_medio_var33_ult1
  type: number
- name: saldo_medio_var33_ult3
  type: number
- name: saldo_medio_var44_hace2
  type: number
- name: saldo_medio_var44_hace3
  type: number
- name: saldo_medio_var44_ult1
  type: number
- name: saldo_medio_var44_ult3
  type: number
- name: var38
  type: number
model_type: gbm
output_features:
- name: TARGET
  type: binary
preprocessing:
  split:
    type: fixed
