input_features:
  - name: Pclass
    type: category
  - name: Sex
    type: category
  - name: Age
    type: numerical
    preprocessing:
      missing_value_strategy: fill_with_mean
  - name: SibSp
    type: numerical
  - name: Parch
    type: numerical
  - name: Fare
    type: numerical
    preprocessing:
      missing_value_strategy: fill_with_mean
  - name: Embarked
    type: category

output_features:
  - name: Survived
    type: binary

training:
  learning_rate: 0.001
  optimizaer:
    type: adam
hyperopt:
  strategy:
    type: grid
    num_samples: 10
  executor:
    type: parallel
    num_workers: 4
  parameters:
    training.learning_rate:
      type: float
      low: 0.0001
      high: 0.1
      steps: 4
      scale: log
    # combiner.num_fc_layers:
    #   type: int
    #   low: 0
    #   high: 5
    # utterance.cell_type:
    #   type: category
    #   values: [rnn, gru, lstm]
