version: 1.0
download_urls:
  - https://firebasestorage.googleapis.com/v0/b/mtl-sentence-representations.appspot.com/o/data%2FSST-2.zip?alt=media&token=aabc5f6b-e466-44a2-b9b4-cf6337f84ac8
split_filenames:
  train_file: train.csv
  test_file: test.csv
  val_file: dev.csv
download_file_type: csv
csv_filename: sst2.csv