hyperopt:
  # goal: maximize
  parameters:
    trainer.learning_rate:
      space: choice
      categories: [0.00002, 0.00003, 0.00005]
    trainer.batch_size:
      space: choice
      categories: [8, 16, 32, 64, 128]
