model_name:
    ui_display_name: Model Name
    expected_impact: 3
generation:
  temperature:
    ui_display_name: Temperature
    default_value_reasoning:
      Increasing the temperature will allow the model to generate more diverse sequences,
      but will also increase the likelihood of generating nonsense. As such, we recommend setting this value to
      something closer to 0 for classification tasks, and something closer to 1 for text generation tasks where the
      goal is to generate novel text.
    expected_impact: 3
  max_new_tokens:
    ui_display_name: Max New Tokens
    default_value_reasoning:
      Increasing the maximum number of new tokens will allow the model
      to generate longer sequences, but because inference time scales linearly with the sequence length,
      longer sequences will be much slower to generate. For classification tasks, it's generally better to
      use a smaller number of new tokens, while for text generation tasks, it's generally better to use a larger
      number of new tokens.
    expected_impact: 3
  num_beams:
    ui_display_name: Number of Beams
    default_value_reasoning:
      Increasing the number of beams will allow the model to generate more diverse sequences,
      but will also increase inference time. Some backends (like DeepSpeed) also do not support beam search.
      As such, we recommend leaving this as 1 in most cases, unless you're finding the quality of the generated
      sequences to be lacking.
    expected_impact: 2
  top_k:
    ui_display_name: Top K
    expected_impact: 2
  top_p:
    ui_display_name: Top P
    expected_impact: 2
  max_length:
    ui_display_name: Max Length
    expected_impact: 2
  min_length:
    ui_display_name: Min Length
    expected_impact: 2
  min_new_tokens:
    ui_display_name: Min New Tokens
    expected_impact: 2
  do_sample:
    ui_display_name: Do Sample
    expected_impact: 2
  use_cache:
    ui_display_name: Use Cache
    expected_impact: 2
prompt:
  retrieval:
    type:
      ui_display_name: Type
      expected_impact: 3
    index_name:
      ui_display_name: Index Name
      expected_impact: 2
    model_name:
      ui_display_name: Model Name
      expected_impact: 2
    k:
      ui_display_name: Top K
      expected_impact: 2
  task:
    ui_display_name: Task
    ui_component_type: textarea
    expected_impact: 3
  template:
    ui_display_name: Template
    ui_component_type: textarea
    expected_impact: 3
adapter:
  lora:
    r:
      ui_display_name: R
      expected_impact: 3
    alpha:
      ui_display_name: Alpha
      expected_impact: 2
    dropout:
      ui_display_name: Dropout
      expected_impact: 2
  prompt_learning:
    num_virtual_tokens:
      ui_display_name: Num Virtual Tokens
      expected_impact: 3
  prompt_tuning:
    prompt_tuning_init:
      ui_display_name: Prompt Tuning Init
      expected_impact: 2
    prompt_tuning_init_text:
      ui_display_name: Prompt Tuning Init Text
      expected_impact: 2
  adaption_prompt:
    adapter_len:
      ui_display_name: Adapter Length
      expected_impact: 3
    adapter_layers:
      ui_display_name: Adapter Layers
      expected_impact: 3
