MSELoss:
  weight:
    expected_impact: 3
MAELoss:
  weight:
    expected_impact: 3
RMSELoss:
  weight:
    expected_impact: 3
RMSPELoss:
  weight:
    expected_impact: 3
BWCEWLoss:
  positive_class_weight:
    expected_impact: 3
  robust_lambda:
    expected_impact: 2
  confidence_penalty:
    expected_impact: 2
  weight:
    expected_impact: 3
SoftmaxCrossEntropyLoss:
  class_weights:
    expected_impact: 3
  robust_lambda:
    expected_impact: 2
  confidence_penalty:
    expected_impact: 2
  class_similarities:
    expected_impact: 2
  class_similarities_temperature:
    expected_impact: 2
  weight:
    expected_impact: 3
SequenceSoftmaxCrossEntropyLoss:
  class_weights:
    expected_impact: 3
  robust_lambda:
    expected_impact: 2
  confidence_penalty:
    expected_impact: 2
  class_similarities:
    expected_impact: 2
  class_similarities_temperature:
    expected_impact: 2
  weight:
    expected_impact: 3
  unique:
    expected_impact: 2
SigmoidCrossEntropyLoss:
  class_weights:
    expected_impact: 3
  weight:
    expected_impact: 3
