output_features:
  - name: label
    type: binary
    weight_regularization: null
input_features:
  - name: lepton_pT
    type: numerical
  - name: lepton_eta
    type: numerical
  - name: lepton_phi
    type: numerical
  - name: missing_energy_magnitude
    type: numerical
  - name: missing_energy_phi
    type: numerical
  - name: jet_1_pt
    type: numerical
  - name: jet_1_eta
    type: numerical
  - name: jet_1_phi
    type: numerical
  - name: jet_1_b-tag
    type: numerical
  - name: jet_2_pt
    type: numerical
  - name: jet_2_eta
    type: numerical
  - name: jet_2_phi
    type: numerical
  - name: jet_2_b-tag
    type: numerical
  - name: jet_3_pt
    type: numerical
  - name: jet_3_eta
    type: numerical
  - name: jet_3_phi
    type: numerical
  - name: jet_3_b-tag
    type: numerical
  - name: jet_4_pt
    type: numerical
  - name: jet_4_eta
    type: numerical
  - name: jet_4_phi
    type: numerical
  - name: jet_4_b-tag
    type: numerical
  - name: m_jj
    type: numerical
  - name: m_jjj
    type: numerical
  - name: m_lv
    type: numerical
  - name: m_jlv
    type: numerical
  - name: m_bb
    type: numerical
  - name: m_wbb
    type: numerical
  - name: m_wwbb
    type: numerical
combiner:
  type: tabnet
  bn_momentum: 0.95
  bn_virtual_bs: 1024
  dropout: 0.05252744300130521
  fc_size: 128
  num_fc_layers: 3
  num_steps: 3
  output_size: 128
  relaxation_factor: 1.5
  size: 32
  sparsity: 0.0001
training:
  batch_size: 8192
  decay_rate: 0.8
  decay_steps: 20000
  learning_rate: 0.01
  shuffle_buffer_size: 1000000
  should_shuffle: true
  eval_batch_size: 500000 #4096 # 65536 131072 262144 524288
  epochs: 300
  early_stop: 30
  optimizer:
    type: adam
  decay: true
  regularization_lambda: 1
  validation_field: label
