version: 1.0
competition: santander-customer-satisfaction
archive_filename: santander-customer-satisfaction.zip
split_filenames:
  train_file: train.csv
csv_filename: train.csv
download_file_type: csv
