version: 1.0
name: connect4
kaggle_dataset_id: tbrewer/connect-4
archive_filenames: connect-4.zip
dataset_filenames: c4_game_database.csv
sha256:
  connect-4.zip: 46c33c47f2664948a4abe53bafee92a602773f31db615bc8bd239e1f98a3d2cf
description: |
  Each row represents the end results of a Connect-4 game.
  Columns 1-42 are the positions on the grid from left to right, top to bottom. Each element in these columns represent to player's piece : 1, and -1, 0 marks an empty cell.
  Column 43 marks the winner of the game : -1, 1, and 0 for tie games.
columns:
  - name: pos_01
    type: number
  - name: pos_02
    type: number
  - name: pos_03
    type: number
  - name: pos_04
    type: number
  - name: pos_05
    type: number
  - name: pos_06
    type: number
  - name: pos_07
    type: number
  - name: pos_08
    type: number
  - name: pos_09
    type: number
  - name: pos_10
    type: number
  - name: pos_11
    type: number
  - name: pos_12
    type: number
  - name: pos_13
    type: number
  - name: pos_14
    type: number
  - name: pos_15
    type: number
  - name: pos_16
    type: number
  - name: pos_17
    type: number
  - name: pos_18
    type: number
  - name: pos_19
    type: number
  - name: pos_20
    type: number
  - name: pos_21
    type: number
  - name: pos_22
    type: number
  - name: pos_23
    type: number
  - name: pos_24
    type: number
  - name: pos_25
    type: number
  - name: pos_26
    type: number
  - name: pos_27
    type: number
  - name: pos_28
    type: number
  - name: pos_29
    type: number
  - name: pos_30
    type: number
  - name: pos_31
    type: number
  - name: pos_32
    type: number
  - name: pos_33
    type: number
  - name: pos_34
    type: number
  - name: pos_35
    type: number
  - name: pos_36
    type: number
  - name: pos_37
    type: number
  - name: pos_38
    type: number
  - name: pos_39
    type: number
  - name: pos_40
    type: number
  - name: pos_41
    type: number
  - name: pos_42
    type: number
  - name: winner
    type: number
output_features:
  - name: winner
    type: category
