version: 1.0
name: google_quest_qa
download_urls:
  - https://automl-mm-bench.s3.amazonaws.com/google_quest_qa/train.pq
  - https://automl-mm-bench.s3.amazonaws.com/google_quest_qa/dev.pq
  - https://automl-mm-bench.s3.amazonaws.com/google_quest_qa/test.pq
sha256:
  test.pq: cb1bb5f32374d83ad4ef7feb4e443c9376cdd919cda40057732ef500e9a4ecf3
  train.pq: 92274286ffb759c96bfca77001c10eb323b3531db3a0e178813db9b82e80a12a
  dev.pq: 2e66450215b94dc404eadc7dde83a1eabad9640d946863c298aa2d42c998ed84
train_filenames: train.pq
validation_filenames: dev.pq
test_filenames: test.pq
description: |
  Google QUEST Q&A Labeling
  Improving automated understanding of complex question answer content.
  The data for this competition includes questions and answers from various StackExchange properties.
  https://www.kaggle.com/c/google-quest-challenge/data
columns:
  - name: qa_id
    type: category
  - name: question_title
    type: text
  - name: question_body
    type: text
  - name: question_user_name
    type: category
  - name: question_user_page
    type: category
  - name: answer
    type: text
  - name: answer_user_name
    type: category
  - name: answer_user_page
    type: category
  - name: url
    type: category
  - name: category
    type: category
  - name: host
    type: category
  - name: question_asker_intent_understanding
    type: number
  - name: question_body_critical
    type: number
  - name: question_conversational
    type: number
  - name: question_expect_short_answer
    type: number
  - name: question_fact_seeking
    type: number
  - name: question_has_commonly_accepted_answer
    type: number
  - name: question_interestingness_others
    type: number
  - name: question_interestingness_self
    type: number
  - name: question_multi_intent
    type: number
  - name: question_not_really_a_question
    type: number
  - name: question_opinion_seeking
    type: number
  - name: question_type_choice
    type: number
  - name: question_type_compare
    type: number
  - name: question_type_consequence
    type: number
  - name: question_type_definition
    type: number
  - name: question_type_entity
    type: number
  - name: question_type_instructions
    type: number
  - name: question_type_procedure
    type: number
  - name: question_type_reason_explanation
    type: number
  - name: question_type_spelling
    type: number
  - name: question_well_written
    type: number
  - name: answer_helpful
    type: number
  - name: answer_level_of_information
    type: number
  - name: answer_plausible
    type: number
  - name: answer_relevance
    type: number
  - name: answer_satisfaction
    type: number
  - name: answer_type_instructions
    type: number
  - name: answer_type_procedure
    type: number
  - name: answer_type_reason_explanation
    type: number
  - name: answer_well_written
    type: number
output_features:
  - name: question_type_reason_explanation
    type: category
