version: 1.0
name: iris
download_urls: https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data
sha256:
  iris.data: 6f608b71a7317216319b4d27b4d9bc84e6abd734eda7872b71a458569e2656c0
description: |
  Iris Dataset
  https://archive.ics.uci.edu/ml/datasets/Iris
columns:
  - name: sepal_length_cm
    type: number
  - name: sepal_width_cm
    type: number
  - name: petal_length_cm
    type: number
  - name: petal_width_cm
    type: number
  - name: class
    type: category
output_features:
  - name: class
    type: category
