version: 1.0
name: iris
download_urls: https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data
sha256:
  iris.data: 6f608b71a7317216319b4d27b4d9bc84e6abd734eda7872b71a458569e2656c0
columns:
  - sepal_length_cm
  - sepal_width_cm
  - petal_length_cm
  - petal_width_cm
  - class
description: |
  Iris Dataset
  https://archive.ics.uci.edu/ml/datasets/Iris
output_features:
  - name: class
    type: category
