version: 1.0
name: naval
download_urls: http://archive.ics.uci.edu/ml/machine-learning-databases/00316/UCI%20CBM%20Dataset.zip
sha256:
  UCI%20CBM%20Dataset.zip: 91a3815da80b5ab7e2d5b82ac82f1c2cbf89182c7a65bcdf240db1e014423cb9
dataset_filenames: UCI CBM Dataset/data.txt
loader: naval.NavalLoader
description: |
  Condition Based Maintenance of Naval Propulsion Plants Data Set
  http://archive.ics.uci.edu/ml/datasets/condition+based+maintenance+of+naval+propulsion+plants
columns:
  - name: lp
    type: number
  - name: v
    type: number
  - name: gtt
    type: number
  - name: gtn
    type: number
  - name: ggn
    type: number
  - name: ts
    type: number
  - name: tp
    type: number
  - name: t48
    type: number
  - name: t1
    type: number
  - name: t2
    type: number
  - name: p48
    type: number
  - name: p1
    type: number
  - name: p2
    type: number
  - name: pexh
    type: number
  - name: tic
    type: number
  - name: mf
    type: number
  - name: gtcdsc
    type: number
  - name: gttdsc
    type: number
output_features:
- name: gtcdsc
  type: number
