version: 1.0
name: news_channel
download_urls:
  - https://automl-mm-bench.s3.amazonaws.com/news_channel/train.csv
  - https://automl-mm-bench.s3.amazonaws.com/news_channel/test.csv
sha256:
  test.csv: d48e7261dce69964eb1163c89e05261b8732c676b10de9b40339b2d95559c9c3
  train.csv: 46e433fcf070ec684cfaf30bada482a73637e8dd954edc3e1fe860de8e661055
train_filenames: train.csv
test_filenames: test.csv
description: |
  Online News Popularity Data Set
  This dataset summarizes a heterogeneous set of features about articles
  published by Mashable in a period of two years. The goal is to predict
  the number of shares in social networks (popularity).
  https://archive.ics.uci.edu/ml/datasets/online+news+popularity
output_features:
- name: channel
  type: category
