version: 1.0
name: news_popularity2
download_urls:
  - https://automl-mm-bench.s3.amazonaws.com/news_popularity2/train.csv
  - https://automl-mm-bench.s3.amazonaws.com/news_popularity2/test.csv
sha256:
  test.csv: 276effa981456e187fb1fc07abd8556d240e1a110fc5c096f2ad75a4082d1ccb
  train.csv: 3673a07b87dbe09a9073e5ab83241681f561984269a9dc5411018fd9bca70b71
train_filenames: train.csv
test_filenames: test.csv
description: |
  Online News Popularity Data Set
  This dataset summarizes a heterogeneous set of features about articles
  published by Mashable in a period of two years. The goal is to predict
  the number of shares in social networks (popularity).
  https://archive.ics.uci.edu/ml/datasets/online+news+popularity
columns:
  - name: n_tokens_content
    type: number
  - name: average_token_length
    type: number
  - name: num_keywords
    type: number
  - name: log_shares
    type: number
  - name: article_title
    type: text
output_features:
- name: log_shares
  type: number
