version: 1.0
name: protein
download_urls: http://archive.ics.uci.edu/ml/machine-learning-databases/00265/CASP.csv
sha256:
  CASP.csv: 4277cfcb4e91a181746cbc654f001b57951c9e6a80f4f795fdb5c807e0848f40
description: |
  Physicochemical Properties of Protein Tertiary Structure Data Set.
  https://archive.ics.uci.edu/ml/datasets/Physicochemical+Properties+of+Protein+Tertiary+Structure
columns:
  - name: RMSD
    type: number
  - name: F1
    type: number
  - name: F2
    type: number
  - name: F3
    type: number
  - name: F4
    type: number
  - name: F5
    type: number
  - name: F6
    type: number
  - name: F7
    type: number
  - name: F8
    type: number
  - name: F9
    type: number
output_features:
  - name: RMSD
    type: number
