version: 1.0
name: synthetic_fraud
kaggle_dataset_id: ealaxi/paysim1
archive_filenames: paysim1.zip
sha256:
  paysim1.zip: f7eef9ffad5cfa64a034143a5c9b30491d189420b273d5ad5723ca40b596613d
description: |
  The Synthetic Financial Datasets For Fraud Detection dataset.
  https://www.kaggle.com/ealaxi/paysim1
columns:
  - name: step
    type: category
  - name: type
    type: category
  - name: amount
    type: number
  - name: nameOrig
    type: category
  - name: oldbalanceOrg
    type: number
  - name: newbalanceOrig
    type: number
  - name: nameDest
    type: category
  - name: oldbalanceDest
    type: number
  - name: newbalanceDest
    type: number
  - name: isFraud
    type: binary
  - name: isFlaggedFraud
    type: binary
output_features:
  - name: isFraud
    type: binary
