version: 1.0
name: twitter_bots
kaggle_dataset_id: danieltreiman/twitter-human-bots-dataset
archive_filenames: twitter-human-bots-dataset.zip
dataset_filenames: twitter_human_bots_dataset.csv
sha256:
  twitter-human-bots-dataset.zip: 16ffaad719ebb9688231844a80f92901c5efb1ff96eafeb869dc5de07b323cdd
preserve_paths:
  - profile_images
  - profile_background_images
description: |
  A dataset for Twitter Bot account detection.
  https://www.kaggle.com/datasets/davidmartngutirrez/twitter-bots-accounts
columns:
  - name: created_at
    type: date
  - name: default_profile
    type: binary
  - name: default_profile_image
    type: binary
  - name: description
    type: text
  - name: favourites_count
    type: number
  - name: followers_count
    type: number
  - name: friends_count
    type: number
  - name: geo_enabled
    type: binary
  - name: id
    type: category
  - name: lang
    type: category
  - name: location
    type: category
  - name: profile_background_image_url
    type: category
  - name: profile_image_url
    type: category
  - name: screen_name
    type: category
  - name: statuses_count
    type: number
  - name: verified
    type: binary
  - name: average_tweets_per_day
    type: number
  - name: account_age_days
    type: number
  - name: account_type
    type: category
  - name: profile_image_path
    type: image
  - name: profile_background_image_path
    type: image
output_features:
  - name: account_type
    type: binary
