version: 1.0
competition: amazon-employee-access-challenge
archive_filename: amazon-employee-access-challenge.zip
split_filenames:
  train_file: train.csv
  test_file: test.csv
csv_filename: amazon-employee-access-challenge.csv
