input_features:
  - name: image_path
    type: image
    preprocessing:
      height: 224
      width: 224
      in_memory: true
      num_channels: 3
    encoder: vit
    img_height: 224
    in_channels: 3
    use_pretrained: true
    hidden_size: 768
    num_hidden_layers: 12
    num_attention_heads: 12
    intermediate_size: 3072
  - name: insurance_company
    type: category
    preprocessing:
      missing_value_strategy: fill_with_const
      fill_value: UNKNOWN
  - name: cost_of_vehicle
    type: number
    preprocessing:
      missing_value_strategy: fill_with_mean
      normalization: zscore
  - name: expiry_date
    type: date
    preprocessing:
      missing_value_strategy: fill_with_const
      fill_value: ""
      datetime_format: "%Y-%m-%d"
  - name: min_coverage
    type: number
    preprocessing:
      missing_value_strategy: fill_with_mean
      normalization: zscore
  - name: max_coverage
    type: number
    preprocessing:
      missing_value_strategy: fill_with_mean
      normalization: zscore
  - name: condition
    type: category
    preprocessing:
      missing_value_strategy: fill_with_const
      fill_value: UNKNOWN
combiner:
  type: concat
  num_fc_layers: 3
  output_size: 256
output_features:
  - name: amount
    type: number
    preprocessing:
      normalization: zscore
trainer:
  epochs: 10
  early_stop: 0
  batch_size: 8
preprocessing:
  force_split: false
  split_probabilities: [0.7, 0.1, 0.2]
