version: 1.0
download_urls:
  - https://fever.ai/download/fever/train.jsonl
  - https://fever.ai/download/fever/paper_dev.jsonl
  - https://fever.ai/download/fever/paper_test.jsonl
split_filenames:
  train_file: train.jsonl
  test_file: paper_dev.jsonl
  val_file: paper_test.jsonl
download_file_type: jsonl
csv_filename: fever.csv
