training:
  batch_size: auto #256
  learning_rate: auto #.001
  # validation_metric: accuracy

hyperopt:
  sampler:
    type: ray
    scheduler:
      type: async_hyperband
      time_attr: time_total_s
      # (time_budget_s / num_samples) * 2
      max_t: 600
    num_samples: 20

  executor:
    type: ray
    time_budget_s: 6000
