combiner:
  type: transformer

training:
  batch_size: auto #256
  learning_rate: auto #0.0001
  # validation_metric: accuracy

hyperopt:
  # goal: maximize
  parameters:
    training.learning_rate:
      space: loguniform
      lower: 0.00001
      upper: 0.001
    training.batch_size:
      space: choice
      categories: [8, 16, 32, 64, 128, 256, 512]
    combiner.num_heads:
      space: choice
      categories: [2, 4]
    combiner.dropout:
      space: uniform
      type: float
      lower: 0.1
      upper: 0.5
    combiner.num_layers:
      space: randint
      type: int
      lower: 1
      upper: 6
    combiner.num_fc_layers:
      space: choice
      categories: [1, 2]
    combiner.fc_dropout:
      space: uniform
      type: float
      lower: 0.1
      upper: 0.5

  sampler:
    type: ray
    scheduler:
      type: async_hyperband
      time_attr: time_total_s

    num_samples: 20

  executor:
    type: ray
    time_budget_s: 6000
