input_features:
  - name: Pclass
    type: category
  - name: Sex
    type: category
  - name: Age
    type: number
    preprocessing:
      missing_value_strategy: fill_with_mean
      normalization: zscore
  - name: SibSp
    type: number
    preprocessing:
      missing_value_strategy: fill_with_mean
      normalization: zscore
  - name: Parch
    type: number
    preprocessing:
      missing_value_strategy: fill_with_mean
      normalization: zscore
  - name: Fare
    type: number
    preprocessing:
      missing_value_strategy: fill_with_mean
      normalization: zscore
  - name: Embarked
    type: category

output_features:
  - name: Survived
    type: binary
    fc_layers: [{ output_size: 50 }]
